development:
  adapter: postgresql
  database: blogger_092021_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: blogger_092021_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: blogger_092021_production
  pool: 5
  timeout: 5000